# Enter the prefix of TSV file or the list of several prefixes of TSV files:
# ex. ["VF_input"] or ["VF_input", "OS_input"]
cov_analysis_result:

# Enter the prefix of BAM file:
# ex. "NSCLC-HR-TruQ4_S23.genome_alignment"
bam_sample:

# Enter the name of a BED file containing panel target regions (with extension)
# ex. "nsclc_target_regions.bed"
tagret_regions:

# Enter the name of a BED file containing amplicons (with extension)
# ex. "HPL_amplicons.bed"
designed_amplicons:

# Enter the absolute path to human reference genome:
# ex. "GRCh38_latest_genomic.fna"
# the FAI file is also required to be in the same directory as a FASTA file
ref_genome:

amplicon_type: ["undercovered", "overcovered"]

# Enter the absolute path to working directory (put the BAM-file, BED-files with target regions and amplicons and
# TVS file with coverage analysis result in this folder):
run_dir:

# Enter the absolute path to python-scripts directory:
scripts_dir:

# Enter the absolute path to the sequtils.jar file:
# ex. /some_directories/sequtils.jar
path_to_sequtils:

# Enter the absolute path to analyze_coverage-2.cwl file:
# ex. /some_directories/analyze_coverage-2.cwl
path_to_analyze_cov:

# Enter the threshold for R2 in linear regression:
threshold: 0.85

# Enter the ratio of observed to predicted relative coverage for undercovered amplicons:
under_ratio: 0.5

# Enter the ratio of observed to predicted relative coverage for overcovered amplicons:
over_ratio: 1.3

# Enter the width of the linear regression plot:
lin_reg_width: 10

# Enter the height of the linear regression plot:
lin_reg_height: 6

# Enter the width of the heatmap:
heatmap_width: 15

# Enter the height of the heatmap:
heatmap_height: 6

# Enter the width of LQR plot :
lqr_plot_width: 10

# Enter the height of LQR plot :
lqr_plot_height: 6

# Enter the first point among numbers of reads per amplicon:
first_point:

# Enter the last point among numbers of reads per amplicon:
last_point:

# Enter the number of points:
points:

# Enter the number of amplicon in a panel:
amp_number:

# Enter the quality threshold for LQRs counting:
qv:

# Enter correction coefficient for the number of reads per amplicon
correction_coeff: 15
